In [14]:
import torch

**创建张量**

In [11]:
x = torch.empty(5,3)
x

tensor([[ 0.0000e+00,  0.0000e+00,  2.1019e-44],
        [ 0.0000e+00, -1.0752e-33,  8.1976e-43],
        [ 1.0653e-38,  1.0194e-38,  0.0000e+00],
        [ 0.0000e+00,  2.1019e-44,  0.0000e+00],
        [-9.1001e+33,  8.1976e-43,  8.9082e-39]])

In [12]:
x = torch.rand(5,3)
x

tensor([[0.5447, 0.8207, 0.2529],
        [0.9162, 0.3581, 0.2011],
        [0.1311, 0.0377, 0.3079],
        [0.7253, 0.0445, 0.6432],
        [0.5370, 0.6579, 0.6980]])

In [14]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [16]:
x = torch.tensor([5,5,1])
x

tensor([5, 5, 1])

In [19]:
a = x.new_ones(5,2)

In [21]:
x.size()

torch.Size([3])

In [23]:
x.shape

torch.Size([3])

In [7]:
torch.arange(1,5,0.4)

tensor([1.0000, 1.4000, 1.8000, 2.2000, 2.6000, 3.0000, 3.4000, 3.8000, 4.2000,
        4.6000])

**Tensor操作**<br>
Pytorch操作inplace版本都有后缀`_`

In [10]:
x = torch.ones(5,3)
y = torch.rand(5,3)
print(x+y)
print(torch.add(x,y))
## inplace
y.add_(x)
print(y)

tensor([[1.0828, 1.8285, 1.4950],
        [1.5632, 1.8932, 1.8061],
        [1.1889, 1.7045, 1.4556],
        [1.4150, 1.6735, 1.9975],
        [1.1714, 1.0412, 1.3015]])
tensor([[1.0828, 1.8285, 1.4950],
        [1.5632, 1.8932, 1.8061],
        [1.1889, 1.7045, 1.4556],
        [1.4150, 1.6735, 1.9975],
        [1.1714, 1.0412, 1.3015]])
tensor([[1.0828, 1.8285, 1.4950],
        [1.5632, 1.8932, 1.8061],
        [1.1889, 1.7045, 1.4556],
        [1.4150, 1.6735, 1.9975],
        [1.1714, 1.0412, 1.3015]])


In [13]:
# 转置，矩阵乘法
x.T@y

tensor([[6.4213, 8.1409, 8.0557],
        [6.4213, 8.1409, 8.0557],
        [6.4213, 8.1409, 8.0557]])

**索引**  
索引的结果与原数据`共享内存`，修改一个另一个也会修改  
不开辟新内存

测试：  
`y += 1`与`y = y+1`的区别

In [62]:
x = torch.rand(5,4)
x

tensor([[0.3294, 0.2063, 0.8826, 0.2798],
        [0.4422, 0.6122, 0.5185, 0.6957],
        [0.2189, 0.4358, 0.2512, 0.5488],
        [0.4404, 0.6838, 0.0995, 0.2723],
        [0.6069, 0.5976, 0.9891, 0.6902]])

In [67]:
y = x[0, :]
t = x[1, :]
print('y:',y)
print('t:',t)

y: tensor([1.3294, 1.2063, 1.8826, 1.2798])
t: tensor([0.4422, 0.6122, 0.5185, 0.6957])


In [64]:
y += 1
t = t+1

In [65]:
print('y:',y)
print('t:',t)

y: tensor([1.3294, 1.2063, 1.8826, 1.2798])
t: tensor([1.4422, 1.6122, 1.5185, 1.6957])


In [66]:
print(x)

tensor([[1.3294, 1.2063, 1.8826, 1.2798],
        [0.4422, 0.6122, 0.5185, 0.6957],
        [0.2189, 0.4358, 0.2512, 0.5488],
        [0.4404, 0.6838, 0.0995, 0.2723],
        [0.6069, 0.5976, 0.9891, 0.6902]])


上述实验说明，t=t+1为重新赋值变量，不再与x共享内存，因此x的第二行没有改变  
如何将t指定到原来内存？  

In [68]:
t = x[1, :]
t[:] = t+1
print(x)

tensor([[1.3294, 1.2063, 1.8826, 1.2798],
        [1.4422, 1.6122, 1.5185, 1.6957],
        [0.2189, 0.4358, 0.2512, 0.5488],
        [0.4404, 0.6838, 0.0995, 0.2723],
        [0.6069, 0.5976, 0.9891, 0.6902]])


**改变形状**  
`view`:共享内存  
`reshape`:不共享内存(不保证返回拷贝，不推荐使用)

In [58]:
print('x:',x)
print('size:',x.size())
y = x.view(20)
print(y.size())

x: tensor([[1.4679, 1.8642, 1.7591, 1.3795],
        [0.2949, 0.1147, 0.0117, 0.1598],
        [0.4098, 0.4872, 0.4149, 0.9244],
        [0.2772, 0.6646, 0.7032, 0.0260],
        [0.3342, 0.2727, 0.1458, 0.5806]])
size: torch.Size([5, 4])
torch.Size([20])


In [59]:
y

tensor([1.4679, 1.8642, 1.7591, 1.3795, 0.2949, 0.1147, 0.0117, 0.1598, 0.4098,
        0.4872, 0.4149, 0.9244, 0.2772, 0.6646, 0.7032, 0.0260, 0.3342, 0.2727,
        0.1458, 0.5806])

In [60]:
x.view(-1,5)

tensor([[1.4679, 1.8642, 1.7591, 1.3795, 0.2949],
        [0.1147, 0.0117, 0.1598, 0.4098, 0.4872],
        [0.4149, 0.9244, 0.2772, 0.6646, 0.7032],
        [0.0260, 0.3342, 0.2727, 0.1458, 0.5806]])

In [61]:
## 返回拷贝的方法
x_cp = x.clone().view(20)
x-=1
print(x)
print(x_cp)

tensor([[ 0.4679,  0.8642,  0.7591,  0.3795],
        [-0.7051, -0.8853, -0.9883, -0.8402],
        [-0.5902, -0.5128, -0.5851, -0.0756],
        [-0.7228, -0.3354, -0.2968, -0.9740],
        [-0.6658, -0.7273, -0.8542, -0.4194]])
tensor([1.4679, 1.8642, 1.7591, 1.3795, 0.2949, 0.1147, 0.0117, 0.1598, 0.4098,
        0.4872, 0.4149, 0.9244, 0.2772, 0.6646, 0.7032, 0.0260, 0.3342, 0.2727,
        0.1458, 0.5806])


**广播（同numpy）**PASS

**Tensor与Numpy的相互转换**

1 Tensor转Numpy

In [70]:
a = torch.rand(5,4)
b = a.numpy()
b

array([[0.37617725, 0.16744131, 0.30691737, 0.53862816],
       [0.80388737, 0.23874283, 0.49951774, 0.06150782],
       [0.71596086, 0.38168848, 0.20470095, 0.851902  ],
       [0.26940095, 0.73361844, 0.913117  , 0.90962875],
       [0.8810355 , 0.07751149, 0.09076309, 0.08274001]], dtype=float32)

2 Numpy转Tensor

In [77]:
import numpy as np
a = np.random.rand(5,4)
b = torch.from_numpy(a)
print(b)

tensor([[0.0607, 0.7670, 0.0133, 0.6300],
        [0.4767, 0.0523, 0.4598, 0.0256],
        [0.5335, 0.3378, 0.3320, 0.7147],
        [0.7574, 0.6429, 0.3386, 0.7616],
        [0.5471, 0.0934, 0.3094, 0.1089]], dtype=torch.float64)


In [81]:
# 此方法不共享内存，速度慢
c = torch.tensor(a)

In [82]:
c

tensor([[0.0607, 0.7670, 0.0133, 0.6300],
        [0.4767, 0.0523, 0.4598, 0.0256],
        [0.5335, 0.3378, 0.3320, 0.7147],
        [0.7574, 0.6429, 0.3386, 0.7616],
        [0.5471, 0.0934, 0.3094, 0.1089]], dtype=torch.float64)

**自动求梯度**

In [3]:
x = torch.ones(2,2,requires_grad=True)

In [4]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [9]:
print(x.grad_fn)

None


In [21]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [32]:
y.backward(torch.ones(2,2))
print(x.grad)


tensor([[6., 6.],
        [6., 6.]])


In [33]:
z = 2*x+5
z.backward(torch.ones(2,2))
print(x.grad)

tensor([[8., 8.],
        [8., 8.]])


*grad在反向传播过程中是累加的(accumulated)，这意味着每一次运行反向传播，梯度都会累加之前的梯度，所以一般在反向传播之前需把梯度清零。*

In [35]:
z = 2*x+5
x.grad.data.zero_()
z.backward(torch.ones(2,2))
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])


在y.backward()时，如果y是标量，则不需要为backward()传入任何参数；否则，需要传入一个与y同形的Tensor