In [4]:
import torch
from torch import nn
from torch.nn import init

#### 自定义参数进行运算

In [2]:
class MyDense(nn.Module):
    def __init__(self):
        super().__init__()
        self.params = nn.ParameterList([nn.Parameter(torch.randn(4, 4)) for i in range(3)])
        self.params.append(nn.Parameter(torch.randn(4, 1)))
    
    def forward(self, x):
        for i in range(len(self.params)):
            x = torch.mm(x, self.params[i])
        return x
net = MyDense()
print(net)

MyDense(
  (params): ParameterList(
      (0): Parameter containing: [torch.FloatTensor of size 4x4]
      (1): Parameter containing: [torch.FloatTensor of size 4x4]
      (2): Parameter containing: [torch.FloatTensor of size 4x4]
      (3): Parameter containing: [torch.FloatTensor of size 4x1]
  )
)


In [ ]:
for name, param in net.named_parameters():
        init.normal_(param, mean=0, std=0.01)
        print(name, param)

params.0 Parameter containing:
tensor([[-0.0024, -0.0060, -0.0015, -0.0111],
        [ 0.0093,  0.0058, -0.0122,  0.0040],
        [-0.0059, -0.0057, -0.0236, -0.0102],
        [-0.0045, -0.0150,  0.0076,  0.0050]], requires_grad=True)
params.1 Parameter containing:
tensor([[-8.1670e-03, -7.0975e-03,  1.6915e-02,  1.2317e-02],
        [ 9.9481e-03, -9.0809e-03,  9.3565e-03,  3.6643e-03],
        [-7.1118e-03,  2.5254e-03, -1.4092e-02,  1.0805e-02],
        [-5.0319e-05, -1.0523e-02,  1.3209e-03,  8.1885e-03]],
       requires_grad=True)
params.2 Parameter containing:
tensor([[-0.0007, -0.0153,  0.0002,  0.0015],
        [ 0.0104, -0.0062,  0.0060, -0.0080],
        [-0.0058, -0.0115,  0.0133, -0.0096],
        [-0.0001, -0.0103,  0.0047, -0.0079]], requires_grad=True)
params.3 Parameter containing:
tensor([[-0.0217],
        [-0.0147],
        [ 0.0054],
        [ 0.0068]], requires_grad=True)
