## 池化层(Pooling)
实际图像中，感兴趣的物体不会总出现在固定位置：即使连续拍摄同一个物体也极有可能出现像素位置上的偏移。这会导致同一个边缘对应的输出可能出现在卷积输出中的不同位置，对模式识别造成不便<br>
提出池化层(pooling)的目的：**缓解卷积层对位置的过度敏感性**

In [1]:
import torch
from torch import nn

In [2]:
def pool2d(X, pool_size, mode='max'):
    X = X.float()
    p_h, p_w = pool_size
    Y = torch.zeros(X.shape[0] - p_h + 1, X.shape[1] - p_w + 1)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i: i+p_h, j: j+p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
    return Y

In [5]:
X = torch.tensor([[0,1,2],[3,4,5],[6,7,8]])
pool2d(X, (2,2))

tensor([[4., 5.],
        [7., 8.]])

#### 加入批量和通道

In [6]:
X = torch.arange(16, dtype=torch.float).view((1,1,4,4))

In [7]:
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [8]:
pool2d = nn.MaxPool2d(3)# 默认步幅为3

In [9]:
pool2d(X)

tensor([[[[10.]]]])

In [10]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [11]:
pool2d = nn.MaxPool2d((2, 4), padding=(1, 2), stride=(2, 3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

## 多通道

**池化层对每个输入通道分别池化，而不是像卷积层那样将各通道的输入按通道相加**<br>
`因此池化层的输出通道数与输入通道数相等`

In [12]:
X = torch.cat((X, X+1), dim=1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [14]:
X.size()

torch.Size([1, 2, 4, 4])

In [15]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])